// Application constants
export const EMAIL_ADDRESSES = {
  SUPPORT: process.env.NEXT_PUBLIC_SUPPORT_EMAIL || 'support@bellregistry.com',
} as const;

export const PROFESSIONAL_ROLES = [
  "Administrative Assistant",
  "Butler",
  "Chief of Staff",
  "Construction Manager",
  "Director of Operations",
  "Director of Real Estate and Construction",
  "Director of Residences",
  "Drop-Off Chef",
  "Driver",
  "Estate Couple",
  "Estate Hospitality Manager",
  "Estate IT Director",
  "Estate Manager",
  "Estate Security Director",
  "Event Chef",
  "Executive Assistant",
  "Executive Housekeeper",
  "Executive Protection",
  "Facilities Manager",
  "Family Assistant",
  "Family Office CEO",
  "Family Office COO",
  "Flight Attendant",
  "Governess",
  "Head Gardener",
  "House Manager",
  "Housekeeper",
  "Houseman",
  "Human Resources Director",
  "Jet Chef",
  "Landscape Director",
  "Laundress",
  "Nanny",
  "Nanny | Educator",
  "Office Chef",
  "Office Manager",
  "Other",
  "Personal Assistant",
  "Personal Chef",
  "Private Chef",
  "Private Teacher",
  "Property Caretaker",
  "Property Manager",
  "Seasonal Chef",
  "Yacht Captain",
  "Yacht Chef",
  "Yacht Engineer",
  "Yacht Steward | Stewardess"
] as const;