import { PrismaClient, UserRole } from '@prisma/client'
import { generateProfileSlug } from '../src/lib/utils'

const prisma = new PrismaClient()

// Array of locations from the main seed file
const locations = [
  'New York, NY',
  'Los Angeles, CA',
  'Miami, FL',
  'San Francisco, CA',
  'Chicago, IL',
  'Boston, MA',
  'Houston, TX',
  'Washington, DC',
  'Seattle, WA',
  'Beverly Hills, CA',
  'Greenwich, CT',
  'Palm Beach, FL',
  'Aspen, CO',
  'Hamptons, NY',
  'Newport, RI',
  "Martha's Vineyard, MA",
  'Lake Tahoe, CA',
  'Scottsdale, AZ',
  'Dallas, TX',
  'Naples, FL'
]

// Professional profiles data
const professionals = [
  {
    firstName: 'James',
    lastName: 'Sullivan',
    title: 'Private Chef',
    location: 'New York, NY',
    yearsOfExperience: 15,
    bio: 'Classically trained French chef with experience in Michelin-starred restaurants and private estates. Specializes in farm-to-table cuisine and wine pairing.',
    skills: ['French Cuisine', 'Menu Planning', 'Wine Pairing', 'Special Dietary Requirements', 'Event Planning'],
    certifications: ['Culinary Institute of America Graduate', 'Level 3 WSET', 'ServSafe Certification'],
    preferredRole: 'Private Chef',
    workLocations: ['New York', 'Hamptons', 'Connecticut'],
    seekingOpportunities: ['Private Chef', 'Personal Chef', 'Estate Chef'],
  },
  {
    firstName: 'Elizabeth',
    lastName: 'Parker',
    title: 'Senior Estate Manager',
    location: 'Los Angeles, CA',
    yearsOfExperience: 12,
    bio: 'Seasoned estate manager with expertise in managing multiple properties and coordinating large household staff. Strong background in project management and vendor relations.',
    skills: ['Staff Management', 'Property Maintenance', 'Event Coordination', 'Budget Management', 'Vendor Relations'],
    certifications: ['Estate Management Professional', 'Project Management Professional'],
    preferredRole: 'Estate Manager',
    workLocations: ['Los Angeles', 'Beverly Hills', 'Santa Barbara'],
    seekingOpportunities: ['Estate Manager', 'Property Manager', 'Director of Residences'],
  },
  {
    firstName: 'William',
    lastName: 'Chen',
    title: 'Executive Protection Specialist',
    location: 'Miami, FL',
    yearsOfExperience: 20,
    bio: 'Former military officer with extensive experience in executive protection and security management for UHNW families. Expertise in international travel security and risk assessment.',
    skills: ['Executive Protection', 'Risk Assessment', 'Security Planning', 'International Travel Security', 'Staff Training'],
    certifications: ['CPP Certification', 'Executive Protection Specialist', 'Advanced Driving Course'],
    preferredRole: 'Executive Protection',
    workLocations: ['Miami', 'New York', 'International'],
    seekingOpportunities: ['Executive Protection', 'Estate Security Director', 'Security Consultant'],
  },
  {
    firstName: 'Sofia',
    lastName: 'Martinez',
    title: 'Trilingual Governess',
    location: 'Greenwich, CT',
    yearsOfExperience: 8,
    bio: 'Experienced governess fluent in English, Spanish, and French. Masters in Early Childhood Education with focus on developmental psychology.',
    skills: ['Early Childhood Education', 'Language Instruction', 'Curriculum Development', 'Child Development', 'Educational Planning'],
    certifications: ['M.Ed. Early Childhood Education', 'Montessori Certification', 'First Aid & CPR'],
    preferredRole: 'Governess',
    workLocations: ['Greenwich', 'New York', 'International'],
    seekingOpportunities: ['Governess', 'Private Teacher', 'Nanny | Educator'],
  },
  {
    firstName: 'Richard',
    lastName: 'Thompson',
    title: 'Butler & House Manager',
    location: 'Palm Beach, FL',
    yearsOfExperience: 25,
    bio: 'Traditional British-trained butler with extensive experience in formal service. Expert in wine cellar management and formal dining protocols.',
    skills: ['Formal Service', 'Wine Service', 'Staff Training', 'Household Management', 'Event Planning'],
    certifications: ['Guild of Professional English Butlers', 'Wine & Spirit Education Trust Level 3'],
    preferredRole: 'Butler',
    workLocations: ['Palm Beach', 'New York', 'London'],
    seekingOpportunities: ['Butler', 'House Manager', 'Estate Manager'],
  },
  {
    firstName: 'Marie',
    lastName: 'DuBois',
    title: 'Executive Housekeeper',
    location: 'San Francisco, CA',
    yearsOfExperience: 10,
    bio: 'Detail-oriented executive housekeeper with experience managing luxury residences and supervising housekeeping teams. Specializes in fine textile care and formal entertaining preparation.',
    skills: ['Team Leadership', 'Inventory Management', 'Quality Control', 'Fine Textile Care', 'Event Preparation'],
    certifications: ['Professional Housekeeping Certification', 'Textile Care Specialist', 'First Aid Certified'],
    preferredRole: 'Executive Housekeeper',
    workLocations: ['San Francisco', 'Napa Valley', 'Lake Tahoe'],
    seekingOpportunities: ['Executive Housekeeper', 'Head Housekeeper', 'House Manager'],
  },
  {
    firstName: 'Alexander',
    lastName: 'Wright',
    title: 'Executive Personal Assistant',
    location: 'Chicago, IL',
    yearsOfExperience: 7,
    bio: 'Detail-oriented personal assistant with experience supporting C-level executives. Strong background in calendar management and travel coordination.',
    skills: ['Calendar Management', 'Travel Planning', 'Event Coordination', 'Project Management', 'Communication'],
    certifications: ['Certified Administrative Professional', 'Project Management Certification'],
    preferredRole: 'Personal Assistant',
    workLocations: ['Chicago', 'New York', 'Remote'],
    seekingOpportunities: ['Personal Assistant', 'Executive Assistant', 'Chief of Staff'],
  },
  {
    firstName: 'Victoria',
    lastName: 'Hughes',
    title: 'Yacht Stewardess',
    location: 'Newport, RI',
    yearsOfExperience: 12,
    bio: 'Experienced yacht professional with extensive knowledge of maritime service and guest relations. Specializes in luxury hospitality and crew management.',
    skills: ['Maritime Service', 'Crew Management', 'Interior Design', 'Event Planning', 'Guest Relations'],
    certifications: ['STCW Certification', 'Silver Service Certification', 'Wine & Spirit Education Trust Level 2'],
    preferredRole: 'Yacht Steward | Stewardess',
    workLocations: ['Newport', 'Mediterranean', 'Caribbean'],
    seekingOpportunities: ['Yacht Steward | Stewardess', 'Interior Manager', 'Guest Relations'],
  },
  {
    firstName: 'David',
    lastName: 'Foster',
    title: 'Head Gardener & Landscape Manager',
    location: 'Greenwich, CT',
    yearsOfExperience: 18,
    bio: 'Master gardener with expertise in landscape design, horticulture, and estate grounds management. Specializes in sustainable practices and seasonal garden planning.',
    skills: ['Landscape Design', 'Horticulture', 'Grounds Management', 'Sustainable Practices', 'Team Leadership'],
    certifications: ['Master Gardener Certification', 'Landscape Design Professional', 'Pesticide Applicator License'],
    preferredRole: 'Head Gardener',
    workLocations: ['Greenwich', 'Hamptons', 'Connecticut'],
    seekingOpportunities: ['Head Gardener', 'Landscape Director', 'Grounds Manager'],
  },
  {
    firstName: 'Isabella',
    lastName: 'Romano',
    title: 'Private Flight Attendant',
    location: 'Los Angeles, CA',
    yearsOfExperience: 9,
    bio: 'Luxury private aviation professional with experience on various aircraft types. Expertise in high-end service and international protocols.',
    skills: ['In-Flight Service', 'Safety Procedures', 'Menu Planning', 'Wine Service', 'International Etiquette'],
    certifications: ['FAA Certification', 'Advanced First Aid', 'Food Safety Manager'],
    preferredRole: 'Flight Attendant',
    workLocations: ['Los Angeles', 'New York', 'International'],
    seekingOpportunities: ['Flight Attendant', 'Corporate Aviation', 'Private Jet Service'],
  },
  {
    firstName: 'Marcus',
    lastName: 'Bennett',
    title: 'Executive Protection Specialist',
    location: 'Beverly Hills, CA',
    yearsOfExperience: 15,
    bio: 'Former Special Forces operator with extensive experience in VIP protection. Specialized in international security operations and threat assessment.',
    skills: ['Executive Protection', 'Threat Assessment', 'Security Planning', 'Defensive Driving', 'Crisis Management'],
    certifications: ['Executive Protection Institute', 'Advanced Defensive Driving', 'EMT Certified'],
    preferredRole: 'Executive Protection',
    workLocations: ['Beverly Hills', 'International', 'New York'],
    seekingOpportunities: ['Executive Protection', 'Estate Security Director', 'Security Consultant'],
  },
  {
    firstName: 'Olivia',
    lastName: 'Chang',
    title: 'House Manager',
    location: 'San Francisco, CA',
    yearsOfExperience: 14,
    bio: 'Experienced house manager with strong organizational skills and attention to detail. Expert in coordinating household operations, managing staff schedules, and maintaining luxury residences.',
    skills: ['Household Operations', 'Staff Coordination', 'Maintenance Management', 'Event Planning', 'Budget Management'],
    certifications: ['House Manager Professional', 'Project Management', 'Facilities Management'],
    preferredRole: 'House Manager',
    workLocations: ['San Francisco', 'Silicon Valley', 'Lake Tahoe'],
    seekingOpportunities: ['House Manager', 'Estate Manager', 'Property Manager'],
  },
  {
    firstName: 'Thomas',
    lastName: 'Blackwood',
    title: 'Professional Driver',
    location: 'Napa Valley, CA',
    yearsOfExperience: 16,
    bio: 'Professional chauffeur with extensive experience driving luxury vehicles and providing transportation services for high-profile clients. Specializes in security-conscious driving and route planning.',
    skills: ['Defensive Driving', 'Route Planning', 'Vehicle Maintenance', 'Security Protocols', 'Customer Service'],
    certifications: ['Professional Chauffeur License', 'Defensive Driving Instructor', 'First Aid Certified'],
    preferredRole: 'Driver',
    workLocations: ['Napa Valley', 'San Francisco', 'International'],
    seekingOpportunities: ['Driver', 'Executive Chauffeur', 'Family Driver'],
  },
  {
    firstName: 'Grace',
    lastName: 'Kim',
    title: 'Nanny & Educator',
    location: 'Malibu, CA',
    yearsOfExperience: 8,
    bio: 'Nurturing nanny with background in early childhood education. Experienced in creating educational activities, managing daily routines, and supporting child development.',
    skills: ['Child Care', 'Educational Activities', 'Routine Management', 'Child Development', 'Safety Management'],
    certifications: ['Early Childhood Education', 'CPR & First Aid', 'Nanny Professional Certification'],
    preferredRole: 'Nanny | Educator',
    workLocations: ['Malibu', 'Los Angeles', 'Remote'],
    seekingOpportunities: ['Nanny | Educator', 'Nanny', 'Child Care Specialist'],
  },
  {
    firstName: 'Daniel',
    lastName: 'Morgan',
    title: 'Estate IT Director',
    location: 'Seattle, WA',
    yearsOfExperience: 10,
    bio: 'Technology professional specializing in smart home integration and cybersecurity for luxury estates. Expert in home automation, network security, and tech support.',
    skills: ['Smart Home Technology', 'Network Security', 'Home Automation', 'IT Support', 'System Integration'],
    certifications: ['CEDIA Designer', 'Network Security Professional', 'Smart Home Professional'],
    preferredRole: 'Estate IT Director',
    workLocations: ['Seattle', 'San Francisco', 'Remote'],
    seekingOpportunities: ['Estate IT Director', 'Technology Manager', 'Smart Home Specialist'],
  },
  {
    firstName: 'Sophia',
    lastName: 'Petrov',
    title: 'Family Assistant',
    location: 'New York, NY',
    yearsOfExperience: 12,
    bio: 'Dedicated family assistant with experience supporting busy families with children. Expert in organizing family schedules, coordinating activities, and providing reliable support.',
    skills: ['Family Coordination', 'Schedule Management', 'Child Care Support', 'Event Planning', 'Organization'],
    certifications: ['Family Assistant Professional', 'CPR & First Aid', 'Child Development Associate'],
    preferredRole: 'Family Assistant',
    workLocations: ['New York', 'Miami', 'International'],
    seekingOpportunities: ['Family Assistant', 'Personal Assistant', 'Household Coordinator'],
  },
  {
    firstName: 'Lucas',
    lastName: 'Rivera',
    title: 'Yacht Captain',
    location: 'Miami, FL',
    yearsOfExperience: 11,
    bio: 'Licensed yacht captain with extensive experience commanding luxury vessels. Expert in navigation, crew management, and providing exceptional guest experiences on the water.',
    skills: ['Yacht Operations', 'Navigation', 'Crew Management', 'Maritime Safety', 'Guest Services'],
    certifications: ['Master 200GT License', 'STCW Certification', 'MCA Certified'],
    preferredRole: 'Yacht Captain',
    workLocations: ['Miami', 'Caribbean', 'International'],
    seekingOpportunities: ['Yacht Captain', 'Marine Operations', 'Fleet Manager'],
  },
  {
    firstName: 'Emma',
    lastName: 'Sinclair',
    title: 'Laundress Specialist',
    location: 'Beverly Hills, CA',
    yearsOfExperience: 9,
    bio: 'Professional laundress with expertise in fine textile care and garment preservation. Specializes in luxury clothing, delicate fabrics, and wardrobe management.',
    skills: ['Fine Textile Care', 'Garment Preservation', 'Stain Removal', 'Wardrobe Organization', 'Fabric Knowledge'],
    certifications: ['Textile Care Professional', 'Dry Cleaning Specialist', 'Garment Care Expert'],
    preferredRole: 'Laundress',
    workLocations: ['Beverly Hills', 'West Hollywood', 'International'],
    seekingOpportunities: ['Laundress', 'Wardrobe Manager', 'Textile Specialist'],
  },
  {
    firstName: 'Benjamin',
    lastName: 'Crawford',
    title: 'Construction Manager',
    location: 'Dallas, TX',
    yearsOfExperience: 17,
    bio: 'Experienced construction manager specializing in luxury residential projects and estate renovations. Expert in project coordination, quality control, and vendor management.',
    skills: ['Construction Management', 'Project Coordination', 'Quality Control', 'Vendor Relations', 'Budget Management'],
    certifications: ['Construction Management Professional', 'OSHA 30 Certified', 'Project Management Professional'],
    preferredRole: 'Construction Manager',
    workLocations: ['Dallas', 'New York', 'International'],
    seekingOpportunities: ['Construction Manager', 'Project Manager', 'Facilities Manager'],
  },
  {
    firstName: 'Natalie',
    lastName: 'Windsor',
    title: 'Executive Assistant',
    location: 'Palm Beach, FL',
    yearsOfExperience: 13,
    bio: 'Highly organized executive assistant with experience supporting UHNW individuals and families. Expert in complex calendar management, travel coordination, and confidential communications.',
    skills: ['Calendar Management', 'Travel Coordination', 'Project Management', 'Communication', 'Confidentiality'],
    certifications: ['Certified Administrative Professional', 'Project Management Professional', 'Executive Assistant Certification'],
    preferredRole: 'Executive Assistant',
    workLocations: ['Palm Beach', 'New York', 'Hamptons'],
    seekingOpportunities: ['Executive Assistant', 'Personal Assistant', 'Chief of Staff'],
  },
  {
    firstName: 'Christopher',
    lastName: 'Sterling',
    title: 'Yacht Engineer',
    location: 'Fort Lauderdale, FL',
    yearsOfExperience: 15,
    bio: 'Marine engineer with extensive experience in yacht mechanical systems and maintenance. Expert in engine repair, electrical systems, and vessel operations.',
    skills: ['Marine Engineering', 'Engine Maintenance', 'Electrical Systems', 'Hydraulics', 'Troubleshooting'],
    certifications: ['Marine Engineer License', 'STCW Certification', 'Marine Electrical Specialist'],
    preferredRole: 'Yacht Engineer',
    workLocations: ['Fort Lauderdale', 'Mediterranean', 'Caribbean'],
    seekingOpportunities: ['Yacht Engineer', 'Marine Technician', 'Fleet Engineer'],
  },
  {
    firstName: 'Amelia',
    lastName: 'Fairfax',
    title: 'Private Teacher',
    location: 'Washington, DC',
    yearsOfExperience: 20,
    bio: 'Certified private teacher with Masters in Education and experience in personalized learning programs. Specializes in curriculum development and academic enrichment.',
    skills: ['Curriculum Development', 'Personalized Learning', 'Academic Assessment', 'Educational Technology', 'Student Mentoring'],
    certifications: ['M.Ed. Curriculum & Instruction', 'Teaching Credential', 'Gifted Education Specialist'],
    preferredRole: 'Private Teacher',
    workLocations: ['Washington DC', 'New York', 'International'],
    seekingOpportunities: ['Private Teacher', 'Educational Consultant', 'Academic Tutor'],
  },
  {
    firstName: 'Harrison',
    lastName: 'Pierce',
    title: 'Property Manager',
    location: 'Greenwich, CT',
    yearsOfExperience: 14,
    bio: 'Experienced property manager specializing in luxury mountain residences and seasonal properties. Expert in maintenance coordination, vendor management, and property care.',
    skills: ['Property Maintenance', 'Vendor Management', 'Seasonal Preparation', 'Budget Planning', 'Emergency Response'],
    certifications: ['Property Management Professional', 'Mountain Property Specialist', 'HVAC Certified'],
    preferredRole: 'Property Manager',
    workLocations: ['Greenwich', 'Hamptons', 'International'],
    seekingOpportunities: ['Property Manager', 'Estate Caretaker', 'Facilities Manager'],
  },
  {
    firstName: 'Charlotte',
    lastName: 'Beaumont',
    title: 'Housekeeper',
    location: 'Boston, MA',
    yearsOfExperience: 11,
    bio: 'Professional housekeeper with experience in luxury residential cleaning and maintenance. Specializes in attention to detail, discretion, and maintaining pristine environments.',
    skills: ['Deep Cleaning', 'Organization', 'Laundry Care', 'Surface Care', 'Inventory Management'],
    certifications: ['Professional Housekeeping Certification', 'Green Cleaning Specialist', 'First Aid Certified'],
    preferredRole: 'Housekeeper',
    workLocations: ['Boston', 'New York', 'International'],
    seekingOpportunities: ['Housekeeper', 'Head Housekeeper', 'Residential Cleaner'],
  },
  {
    firstName: 'Julian',
    lastName: 'Ashworth',
    title: 'Houseman',
    location: 'Aspen, CO',
    yearsOfExperience: 16,
    bio: 'Dedicated houseman with experience in luxury residential care and maintenance. Expert in household repairs, guest services, and supporting daily operations.',
    skills: ['Household Maintenance', 'Guest Services', 'Cleaning Protocols', 'Basic Repairs', 'Inventory Management'],
    certifications: ['Household Professional Certification', 'First Aid Certified', 'Basic Electrical Certification'],
    preferredRole: 'Houseman',
    workLocations: ['Aspen', 'New York', 'International'],
    seekingOpportunities: ['Houseman', 'Household Assistant', 'Property Caretaker'],
  },
  {
    firstName: 'Penelope',
    lastName: 'Rothschild',
    title: 'Office Manager',
    location: 'Manhattan, NY',
    yearsOfExperience: 10,
    bio: 'Professional office manager with experience in family office environments. Expert in administrative operations, vendor coordination, and maintaining efficient office systems.',
    skills: ['Office Administration', 'Vendor Coordination', 'Systems Management', 'Budget Tracking', 'Communication'],
    certifications: ['Office Management Professional', 'Administrative Excellence', 'Family Office Specialist'],
    preferredRole: 'Office Manager',
    workLocations: ['Manhattan', 'Hamptons', 'International'],
    seekingOpportunities: ['Office Manager', 'Administrative Manager', 'Family Office Coordinator'],
  },
  {
    firstName: 'Sebastian',
    lastName: 'Voss',
    title: 'Landscape Director',
    location: 'Santa Barbara, CA',
    yearsOfExperience: 13,
    bio: 'Landscape architect and director with expertise in desert landscaping and estate grounds management. Specializes in sustainable design and water-efficient gardens.',
    skills: ['Landscape Architecture', 'Desert Landscaping', 'Water Management', 'Sustainable Design', 'Project Management'],
    certifications: ['Landscape Architecture License', 'Water Efficiency Specialist', 'Desert Landscape Professional'],
    preferredRole: 'Landscape Director',
    workLocations: ['Santa Barbara', 'Napa Valley', 'International'],
    seekingOpportunities: ['Landscape Director', 'Head Gardener', 'Grounds Manager'],
  },
  {
    firstName: 'Gabrielle',
    lastName: 'Laurent',
    title: 'Personal Chef',
    location: 'Newport, RI',
    yearsOfExperience: 9,
    bio: 'French-trained pastry chef specializing in fine desserts and chocolate work. Experience in menu development and special dietary requirements.',
    skills: ['Pastry Arts', 'Chocolate Work', 'Menu Development', 'Special Diets', 'Event Planning'],
    certifications: ['Le Cordon Bleu Patisserie', 'Chocolate Master', 'Specialty Dietary Training'],
    preferredRole: 'Personal Chef',
    workLocations: ['Newport', 'New York', 'International'],
    seekingOpportunities: ['Personal Chef', 'Private Chef', 'Estate Chef'],
  },
  {
    firstName: 'Maxwell',
    lastName: 'Thorne',
    title: 'Chief of Staff',
    location: 'Silicon Valley, CA',
    yearsOfExperience: 12,
    bio: 'Experienced chief of staff with background in executive support and operations management. Expert in strategic planning, staff coordination, and complex project management.',
    skills: ['Strategic Planning', 'Operations Management', 'Staff Leadership', 'Project Coordination', 'Executive Support'],
    certifications: ['Executive Leadership Certificate', 'Operations Management Professional', 'Strategic Planning Specialist'],
    preferredRole: 'Chief of Staff',
    workLocations: ['Silicon Valley', 'Los Angeles', 'New York'],
    seekingOpportunities: ['Chief of Staff', 'Operations Director', 'Executive Assistant'],
  },
  {
    firstName: 'Elena',
    lastName: 'Rossi',
    title: 'Event Chef',
    location: 'Miami, FL',
    yearsOfExperience: 11,
    bio: 'Innovative event chef specializing in luxury catering and special events. Expert in menu design, presentation, and managing high-profile gatherings.',
    skills: ['Event Catering', 'Menu Design', 'Team Management', 'Food Styling', 'Dietary Accommodations'],
    certifications: ['Culinary Arts Degree', 'Food Safety Manager', 'Wine Pairing Specialist'],
    preferredRole: 'Event Chef',
    workLocations: ['Miami', 'Palm Beach', 'New York'],
    seekingOpportunities: ['Event Chef', 'Private Chef', 'Catering Director'],
  },
  {
    firstName: 'Adrian',
    lastName: 'Blackwood',
    title: 'Estate Security Director',
    location: 'Los Angeles, CA',
    yearsOfExperience: 18,
    bio: 'Former law enforcement professional specializing in estate security and risk management. Expert in security system implementation and staff training.',
    skills: ['Security Management', 'Risk Assessment', 'Staff Training', 'Emergency Response', 'Technology Integration'],
    certifications: ['Security Management Professional', 'Advanced Security Training', 'Crisis Management'],
    preferredRole: 'Estate Security Director',
    workLocations: ['Los Angeles', 'Beverly Hills', 'International'],
    seekingOpportunities: ['Estate Security Director', 'Security Manager', 'Risk Management'],
  },
  {
    firstName: 'Camille',
    lastName: 'Dubois',
    title: 'Drop-Off Chef',
    location: 'San Francisco, CA',
    yearsOfExperience: 8,
    bio: 'Culinary professional specializing in weekly meal preparation and dietary specific cooking. Expert in nutrition and meal planning for busy families.',
    skills: ['Meal Planning', 'Dietary Restrictions', 'Food Safety', 'Recipe Development', 'Nutrition'],
    certifications: ['Nutritional Cooking Certificate', 'Food Safety Manager', 'Dietary Specialist'],
    preferredRole: 'Drop-Off Chef',
    workLocations: ['San Francisco', 'Silicon Valley', 'Bay Area'],
    seekingOpportunities: ['Drop-Off Chef', 'Personal Chef', 'Meal Prep Specialist'],
  },
  {
    firstName: 'Marcus',
    lastName: 'Alvarez',
    title: 'Seasonal Chef',
    location: 'Hamptons, NY',
    yearsOfExperience: 14,
    bio: 'Experienced chef specializing in seasonal residences and summer entertaining. Expert in local ingredients and coastal cuisine.',
    skills: ['Seasonal Cooking', 'Event Planning', 'Staff Management', 'Menu Development', 'Wine Pairing'],
    certifications: ['Culinary Arts Degree', 'Sommelier Level 2', 'Seafood Specialist'],
    preferredRole: 'Seasonal Chef',
    workLocations: ['Hamptons', 'Martha\'s Vineyard', 'Palm Beach'],
    seekingOpportunities: ['Seasonal Chef', 'Private Chef', 'Estate Chef'],
  },
  {
    firstName: 'Rebecca',
    lastName: 'Hamilton',
    title: 'Family Office CEO',
    location: 'Greenwich, CT',
    yearsOfExperience: 22,
    bio: 'Seasoned family office executive with extensive experience in wealth management and family enterprise leadership. Expert in strategic planning and multi-generational wealth preservation.',
    skills: ['Wealth Management', 'Strategic Planning', 'Team Leadership', 'Family Governance', 'Investment Oversight'],
    certifications: ['CFA', 'Family Office Management', 'Wealth Management Professional'],
    preferredRole: 'Family Office CEO',
    workLocations: ['Greenwich', 'New York', 'Palm Beach'],
    seekingOpportunities: ['Family Office CEO', 'Executive Director', 'Wealth Management'],
  },
  {
    firstName: 'Jonathan',
    lastName: 'Price',
    title: 'Family Office COO',
    location: 'Palm Beach, FL',
    yearsOfExperience: 19,
    bio: 'Experienced operations executive specializing in family office management and process optimization. Expert in team building and operational efficiency.',
    skills: ['Operations Management', 'Process Improvement', 'Team Development', 'Risk Management', 'Strategic Planning'],
    certifications: ['MBA', 'Operations Management', 'Project Management Professional'],
    preferredRole: 'Family Office COO',
    workLocations: ['Palm Beach', 'Miami', 'New York'],
    seekingOpportunities: ['Family Office COO', 'Operations Director', 'Family Office Executive'],
  },
  {
    firstName: 'Sarah',
    lastName: 'Mitchell',
    title: 'Administrative Assistant',
    location: 'Boston, MA',
    yearsOfExperience: 6,
    bio: 'Detail-oriented administrative professional with experience in high-net-worth family offices. Strong skills in organization and communication.',
    skills: ['Office Administration', 'Calendar Management', 'Document Preparation', 'Client Relations', 'Data Management'],
    certifications: ['Administrative Professional', 'Microsoft Office Specialist', 'Business Administration'],
    preferredRole: 'Administrative Assistant',
    workLocations: ['Boston', 'New York', 'Remote'],
    seekingOpportunities: ['Administrative Assistant', 'Executive Assistant', 'Office Coordinator'],
  },
  {
    firstName: 'Michael',
    lastName: 'Reynolds',
    title: 'Human Resources Director',
    location: 'Chicago, IL',
    yearsOfExperience: 16,
    bio: 'HR professional specializing in private service and family office staff management. Expert in recruitment, training, and employee relations.',
    skills: ['HR Management', 'Recruitment', 'Employee Relations', 'Training Development', 'Policy Implementation'],
    certifications: ['SHRM-SCP', 'HR Management Professional', 'Diversity & Inclusion'],
    preferredRole: 'Human Resources Director',
    workLocations: ['Chicago', 'New York', 'Remote'],
    seekingOpportunities: ['HR Director', 'People Operations', 'Talent Management'],
  },
  {
    firstName: 'Isabella',
    lastName: 'Santos',
    title: 'Director of Residences',
    location: 'Miami, FL',
    yearsOfExperience: 15,
    bio: 'Experienced property professional managing multiple luxury residences. Expert in staff coordination and property operations.',
    skills: ['Property Management', 'Staff Supervision', 'Project Management', 'Vendor Relations', 'Budget Management'],
    certifications: ['Property Management Professional', 'Real Estate License', 'Facilities Management'],
    preferredRole: 'Director of Residences',
    workLocations: ['Miami', 'Palm Beach', 'New York'],
    seekingOpportunities: ['Director of Residences', 'Estate Manager', 'Property Director'],
  },
  {
    firstName: 'Robert',
    lastName: 'Nash',
    title: 'Estate Hospitality Manager',
    location: 'Beverly Hills, CA',
    yearsOfExperience: 13,
    bio: 'Hospitality professional specializing in luxury estate guest services and event management. Expert in creating exceptional experiences.',
    skills: ['Guest Services', 'Event Planning', 'Staff Training', 'Luxury Hospitality', 'Protocol'],
    certifications: ['Hospitality Management', 'Event Planning Professional', 'Wine Service'],
    preferredRole: 'Estate Hospitality Manager',
    workLocations: ['Beverly Hills', 'Los Angeles', 'International'],
    seekingOpportunities: ['Estate Hospitality Manager', 'Guest Relations Director', 'Events Manager'],
  },
  {
    firstName: 'Katherine',
    lastName: 'Walsh',
    title: 'Director of Operations',
    location: 'New York, NY',
    yearsOfExperience: 17,
    bio: 'Operations professional with extensive experience in estate and household management. Expert in process improvement and staff development.',
    skills: ['Operations Management', 'Team Leadership', 'Process Improvement', 'Project Management', 'Budget Administration'],
    certifications: ['Operations Management', 'Project Management Professional', 'Six Sigma Green Belt'],
    preferredRole: 'Director of Operations',
    workLocations: ['New York', 'Hamptons', 'Connecticut'],
    seekingOpportunities: ['Director of Operations', 'COO', 'Operations Manager'],
  },
  {
    firstName: 'Andrew',
    lastName: 'Barrett',
    title: 'Director of Real Estate and Construction',
    location: 'Los Angeles, CA',
    yearsOfExperience: 20,
    bio: 'Real estate and construction professional specializing in luxury property development and renovation. Expert in project management and contractor coordination.',
    skills: ['Real Estate Development', 'Construction Management', 'Project Planning', 'Vendor Management', 'Budget Control'],
    certifications: ['Real Estate License', 'Construction Management', 'LEED AP'],
    preferredRole: 'Director of Real Estate and Construction',
    workLocations: ['Los Angeles', 'San Francisco', 'New York'],
    seekingOpportunities: ['Real Estate Director', 'Construction Director', 'Development Manager'],
  },
  {
    firstName: 'Claire',
    lastName: 'Montgomery',
    title: 'Facilities Manager',
    location: 'Washington, DC',
    yearsOfExperience: 12,
    bio: 'Facilities professional specializing in luxury property maintenance and systems management. Expert in preventive maintenance and vendor coordination.',
    skills: ['Facilities Management', 'Maintenance Planning', 'Vendor Coordination', 'Safety Compliance', 'Budget Management'],
    certifications: ['Facilities Management Professional', 'HVAC Systems', 'Building Operations'],
    preferredRole: 'Facilities Manager',
    workLocations: ['Washington DC', 'Virginia', 'Maryland'],
    seekingOpportunities: ['Facilities Manager', 'Property Manager', 'Operations Manager'],
  },
  {
    firstName: 'Derek',
    lastName: 'Zhang',
    title: 'Office Chef',
    location: 'San Francisco, CA',
    yearsOfExperience: 10,
    bio: 'Corporate chef specializing in healthy, diverse cuisine for office environments. Expert in dietary accommodations and large-scale meal planning.',
    skills: ['Corporate Catering', 'Menu Planning', 'Dietary Restrictions', 'Team Management', 'Food Safety'],
    certifications: ['Culinary Arts Degree', 'Food Safety Manager', 'Nutrition Specialist'],
    preferredRole: 'Office Chef',
    workLocations: ['San Francisco', 'Silicon Valley', 'Bay Area'],
    seekingOpportunities: ['Office Chef', 'Corporate Chef', 'Catering Manager'],
  },
  {
    firstName: 'Sophia',
    lastName: 'Kowalski',
    title: 'Yacht Chef',
    location: 'Fort Lauderdale, FL',
    yearsOfExperience: 11,
    bio: 'Maritime chef with extensive experience on luxury yachts. Expert in international cuisine and provisioning in remote locations.',
    skills: ['Maritime Cooking', 'Provisioning', 'Menu Planning', 'Dietary Restrictions', 'Inventory Management'],
    certifications: ['Maritime Culinary Certificate', 'STCW', 'Food Safety at Sea'],
    preferredRole: 'Yacht Chef',
    workLocations: ['Fort Lauderdale', 'Mediterranean', 'Caribbean'],
    seekingOpportunities: ['Yacht Chef', 'Private Chef', 'Maritime Culinary'],
  },
  {
    firstName: 'James',
    lastName: 'Harrison',
    title: 'Jet Chef',
    location: 'Las Vegas, NV',
    yearsOfExperience: 13,
    bio: 'Aviation culinary professional specializing in private jet dining. Expert in high-altitude cooking and international cuisine.',
    skills: ['Aviation Catering', 'High-Altitude Cooking', 'Menu Development', 'Food Safety', 'Wine Selection'],
    certifications: ['Aviation Culinary Certificate', 'Food Safety Manager', 'Wine Specialist'],
    preferredRole: 'Jet Chef',
    workLocations: ['Las Vegas', 'Los Angeles', 'International'],
    seekingOpportunities: ['Jet Chef', 'Private Aviation Chef', 'Executive Chef'],
  },
  {
    firstName: 'Olivia',
    lastName: 'Reeves',
    title: 'Estate Couple - Property Manager',
    location: 'Aspen, CO',
    yearsOfExperience: 15,
    bio: 'Part of an experienced estate couple specializing in luxury property management. Expert in household operations and maintenance.',
    skills: ['Property Management', 'Household Operations', 'Maintenance', 'Guest Services', 'Staff Coordination'],
    certifications: ['Property Management', 'Household Management', 'First Aid'],
    preferredRole: 'Estate Couple',
    workLocations: ['Aspen', 'Vail', 'International'],
    seekingOpportunities: ['Estate Couple', 'Property Managers', 'Caretakers'],
  },
  {
    firstName: 'William',
    lastName: 'Reeves',
    title: 'Estate Couple - Chef',
    location: 'Aspen, CO',
    yearsOfExperience: 15,
    bio: 'Part of an experienced estate couple specializing in private chef services and property management. Expert in fine dining and event planning.',
    skills: ['Culinary Arts', 'Event Planning', 'Wine Service', 'Property Maintenance', 'Guest Services'],
    certifications: ['Culinary Arts Degree', 'Wine Service', 'Property Management'],
    preferredRole: 'Estate Couple',
    workLocations: ['Aspen', 'Vail', 'International'],
    seekingOpportunities: ['Estate Couple', 'Property Managers', 'Caretakers'],
  },
  {
    firstName: 'Henry',
    lastName: 'Whitman',
    title: 'Property Caretaker',
    location: 'Martha\'s Vineyard, MA',
    yearsOfExperience: 19,
    bio: 'Experienced property caretaker specializing in seasonal estate maintenance. Expert in building systems and grounds care.',
    skills: ['Property Maintenance', 'Grounds Care', 'Building Systems', 'Security Monitoring', 'Storm Preparation'],
    certifications: ['Property Maintenance Professional', 'HVAC Systems', 'Boat Handling'],
    preferredRole: 'Property Caretaker',
    workLocations: ['Martha\'s Vineyard', 'Nantucket', 'Cape Cod'],
    seekingOpportunities: ['Property Caretaker', 'Estate Manager', 'Facilities Manager'],
  },
  {
    firstName: 'Maria',
    lastName: 'Vasquez',
    title: 'Estate Couple - Housekeeper',
    location: 'Greenwich, CT',
    yearsOfExperience: 14,
    bio: 'Part of an experienced estate couple specializing in formal housekeeping and property maintenance. Expert in fine textile care and silver service.',
    skills: ['Formal Housekeeping', 'Silver Service', 'Fine Textile Care', 'Event Support', 'Inventory Management'],
    certifications: ['Housekeeping Professional', 'Textile Care', 'First Aid'],
    preferredRole: 'Estate Couple',
    workLocations: ['Greenwich', 'Westchester', 'Hamptons'],
    seekingOpportunities: ['Estate Couple', 'Property Managers', 'Caretakers'],
  },
  {
    firstName: 'Carlos',
    lastName: 'Vasquez',
    title: 'Estate Couple - Maintenance',
    location: 'Greenwich, CT',
    yearsOfExperience: 14,
    bio: 'Part of an experienced estate couple specializing in property maintenance and grounds care. Expert in building systems and security.',
    skills: ['Property Maintenance', 'Grounds Care', 'Security Systems', 'Building Systems', 'Project Management'],
    certifications: ['Property Maintenance', 'HVAC Systems', 'Security Systems'],
    preferredRole: 'Estate Couple',
    workLocations: ['Greenwich', 'Westchester', 'Hamptons'],
    seekingOpportunities: ['Estate Couple', 'Property Managers', 'Caretakers'],
  },
  {
    firstName: 'Alexandra',
    lastName: 'Kensington',
    title: 'Nanny',
    location: 'Beverly Hills, CA',
    yearsOfExperience: 10,
    bio: 'Experienced nanny specializing in newborn and infant care. Expert in child development and creating nurturing environments.',
    skills: ['Newborn Care', 'Child Development', 'Sleep Training', 'Activity Planning', 'First Aid'],
    certifications: ['Newborn Care Specialist', 'Child Development Associate', 'CPR & First Aid'],
    preferredRole: 'Nanny',
    workLocations: ['Beverly Hills', 'Los Angeles', 'International'],
    seekingOpportunities: ['Nanny', 'Newborn Specialist', 'Childcare Professional'],
  }
]

async function main() {
  console.log('Creating 50 professional profiles...')
  
  let count = 0
  for (const professional of professionals) {
    // Create user account
    const user = await prisma.user.create({
      data: {
        email: `${professional.firstName.toLowerCase()}.${professional.lastName.toLowerCase()}@example.com`,
        firstName: professional.firstName,
        lastName: professional.lastName,
        role: UserRole.PROFESSIONAL,
        emailVerified: new Date(),
        profileSlug: await generateProfileSlug(professional.firstName, professional.lastName),
      }
    })

    // Create candidate profile
    await prisma.candidateProfile.create({
      data: {
        userId: user.id,
        bio: professional.bio,
        title: professional.title,
        location: professional.location,
        yearsOfExperience: professional.yearsOfExperience,
        skills: professional.skills,
        certifications: professional.certifications,
        preferredRole: professional.preferredRole,
        workLocations: professional.workLocations,
        seekingOpportunities: professional.seekingOpportunities,
        openToWork: true,
        employmentType: 'Full-time'
      }
    })

    count++
    console.log(`Created professional profile ${count}/50: ${professional.firstName} ${professional.lastName}`)
  }

  console.log('Professional profiles seed completed successfully')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  }) 